server:
  port: 9999
  address: 0.0.0.0

# MySQL Configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/planner_db}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update

# Logging configuration
logging:
  level:
    root: info
  file:
    name: logs/planner.log